# Backend API — tradeapi.ziyrak.org
upstream trade_node {
    server 127.0.0.1:3020;
    keepalive 8;
}

upstream trade_django {
    server 127.0.0.1:8020;
    keepalive 4;
}

server {
    listen 80;
    listen [::]:80;
    server_name tradeapi.ziyrak.org;

    client_max_body_size 4m;

    location /admin/ {
        proxy_pass http://trade_django;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        proxy_pass http://trade_django;
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://trade_node;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400;
        proxy_buffering off;
    }
}
