# Frontend HTTP — certbot oldin (trade.tcall.uz)
server {
    listen 80;
    listen [::]:80;
    server_name trade.tcall.uz;

    root /opt/tradetcall/dist-web;
    index index.html;
    client_max_body_size 4m;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
